#!/bin/bash

##########################
# Made by Alberto Lazari #
##########################

# This is a simple script to create a new C++ Project. It creates a new folder containing the folders
# you will need and a Makefile that works out-of-the-box

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJ_NAME=""

# Options
HERE=false
MAKEFILE=false
NO_DIRS=false

printHelp() {
    echo "Usage: mkproj [OPTION] PROJECT"
    echo "Create the C++ PROJECT, if it does not already exist."
    echo ""
    echo "Options:"
    echo "  -h, --help           display this help and exit"
    echo "  -m, --makefile-only  only creates/updates the Makefile"
    echo "      --here           set up the project in the current directory"
    echo "      --no-dirs        does not create src/ and include/ directories"
}

createDir() {
    if [ -e "$1" ]; then
        return 1
    fi
    mkdir "$1"
}

setupDir() {
    cp "$SCRIPT_DIR"/Makefile "$1"/Makefile
    if [ $MAKEFILE = false ] && [ $NO_DIRS = false ]; then
        mkdir "$1"/{src,include}
    fi
    if [ $MAKEFILE = false ]; then
        cp -r "$SCRIPT_DIR"/../.vscode/ "$1"/.vscode/
    fi
}

checkFlags() {
    if [ $# = 0 ] ; then
        return 1
    fi

    while [ $# != 0 ]
    do
        case $1 in
            -h|--help)
                printHelp
                exit
                ;;
            -m|--makefile-only)
                MAKEFILE=true
                ;;
            --here)
                HERE=true
                ;;
            --no-dirs)
                NO_DIRS=true
                ;;
            -*)
                echo "mkproj: unrecognized option '$1'"
                echo "try 'mkproj -h' or 'mkproj --help' for more information."
                exit 1
                ;;
            *)
                PROJ_NAME=$1
                ;;
        esac
        shift
    done
}

if ! checkFlags "$@" || ( [ $HERE = false ] && [ "$PROJ_NAME" = "" ] ); then
    printHelp
    exit 1
fi

if [ $HERE = false ] && ! createDir "$PROJ_NAME"; then
    echo "cannot create project '$PROJ_NAME': File already exists"
    exit 1
fi

if  [ $HERE = false ]; then
    setupDir "$PROJ_NAME"
else
    setupDir "$PWD"
fi
